"""threads and messages

Revision ID: 556de3fe7b46
Revises: e83c29d0aa66
Create Date: 2025-12-31 09:12:03.461125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556de3fe7b46'
down_revision: Union[str, None] = 'e83c29d0aa66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_plan_entitlements_plan_id'), table_name='plan_entitlements')
    op.create_index(op.f('ix_plan_entitlements_plan_id'), 'plan_entitlements', ['plan_id'], unique=False)
    op.drop_constraint(op.f('plan_entitlements_plan_id_fkey'), 'plan_entitlements', type_='foreignkey')
    op.create_foreign_key(None, 'plan_entitlements', 'plans', ['plan_id'], ['id'])
    op.drop_constraint(op.f('plans_code_key'), 'plans', type_='unique')
    op.drop_index(op.f('uq_usage_user_period'), table_name='usage_counters')
    op.drop_constraint(op.f('usage_counters_user_id_fkey'), 'usage_counters', type_='foreignkey')
    op.create_foreign_key(None, 'usage_counters', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_plan_id'), table_name='users')
    op.drop_constraint(op.f('fk_users_plan_id_plans'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_plan_id_plans'), 'users', 'plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_users_plan_id'), 'users', ['plan_id'], unique=False)
    op.drop_constraint(None, 'usage_counters', type_='foreignkey')
    op.create_foreign_key(op.f('usage_counters_user_id_fkey'), 'usage_counters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uq_usage_user_period'), 'usage_counters', ['user_id', 'period_type', 'period_start'], unique=True)
    op.create_unique_constraint(op.f('plans_code_key'), 'plans', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'plan_entitlements', type_='foreignkey')
    op.create_foreign_key(op.f('plan_entitlements_plan_id_fkey'), 'plan_entitlements', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_plan_entitlements_plan_id'), table_name='plan_entitlements')
    op.create_index(op.f('ix_plan_entitlements_plan_id'), 'plan_entitlements', ['plan_id'], unique=True)
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
